"""add phone number

Revision ID: b7abebf9983a
Revises: a528bcbac3ba
Create Date: 2024-06-12 10:03:51.774922
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = 'b7abebf9983a'   # revision identifiers, used by Alembic.
down_revision: Union[str, None] = 'a528bcbac3ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users',sa.Column('phone_number',sa.String(),nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users','phone_number')
    # ### end Alembic commands ###
